### ISSUE TITLE
plugin ignores user browser settings

### ISSUE THREAD

**Issue by limnick** [hlfcoding/sublime-mermaid#2]
Was trying to figure out why some random web browser kept opening instead of my default web browser and tracked it down to this line:
https://github.com/hlfcoding/sublime-mermaid/blob/master/mermaid.py#L21

is there any particular reason it's defaulting to safari here? I'm happy to put in a PR to make it use the system default or allow user to specify using a user setting, but wanted to be sure I understood why safari was locked in place to begin with...

**Comment by limnick** [comment]
also noticed one of the 5 forks of this package was to fix this issue: https://github.com/ZimbiX/sublime-mermaid/commit/dc8257fc1d6cfca30619790659a8bd9b7bae0789

**Comment by hlfcoding** [comment]
No particular reason. IIRC I thought it'd be harder; don't write a lot of Python TBH. Thanks!
